### ISSUE TITLE
Question about predicting sentences in predict_amrs_from_plaintext.py

### ISSUE THREAD

**Issue by cws7777** [SapienzaNLP/spring#10]
Hi, 
First of all, thank you for the great work!

I have a question about predicting sentences in `predict_amrs_from_plaintext.py` (from [L123](https://github.com/SapienzaNLP/spring/blob/39079940d028ba0dde4c1af60432be49f67d76f8/bin/predict_amrs_from_plaintext.py#L123) to  [L139](https://github.com/SapienzaNLP/spring/blob/39079940d028ba0dde4c1af60432be49f67d76f8/bin/predict_amrs_from_plaintext.py#L139)).

Is the code for (plain text version of) AMR-to-Text generation part?

Thanks.

**Comment by mbevila** [comment]
It should allow you to generate a sentence from the generated graphs. If you need this use case, I would not recommend doing it that way, it is commented because it is untested. Also, you're skipping the BLINK wikification step.

**Comment by cws7777** [comment]
I see, thanks!! 😄

**Comment by cws7777** [comment]
Hi, then what if I use `predict_sentences.py` to generate sentences from the generated graphs(I saved this as a text file like AMR dataset) instead of using the commented code in `predict_amrs_from_plaintext.py`?

Are there some things to modify? I think the only difference is `dataset` part?
