### ISSUE TITLE
Question about the changes in AMRBartForConditionalGeneration

### ISSUE THREAD

**Issue by bjascob** [SapienzaNLP/spring#11]
I see that you have a custom `modeling_bart.py` file with `AMRBartForConditionalGeneration`.  It looks like most of the changes revolve around adding "backreferences" but it's difficult to tell since I'm not sure what version of transformers that file originally came from (do you happen to know this?)
* Is there anywhere that explains what's being changed in this class (conceptually)?  I didn't see these modifications explained in your paper "One SPRING to Rule Them Both".  Are they detailed in another place?

My goal is to upgrade to the latest transformers library for compatibility reasons.  This repo trains correctly if I switch to the newest `BartForConditionalGeneration` from the transformers library, but I'm getting smatch scores about 2 points lower than in your paper.  Is this consistent with what you've seen (ie.. does the custom `AMRBartForConditionalGeneration` improve scores by about 2 points?).

**Comment by mbevila** [comment]
Hi, backreferences are fossils of a previous iteration of the SPRING model that did not make it into the paper. They play no part in decoding with the parameters detailed in the README. 

The current code needs to run with Transformers < 3.0. 

It is possible to patch the current code and run with a newer version of Transformers and you replicate exactly the same results in the paper using vanilla `BartForConditionalGeneration`. I can update the repo in a bit, these days I am bit swamped.

**Comment by bjascob** [comment]
Thanks for the info.  I actually have your code running with the latest transformers (4.12) and the standard BartForConditionalGeneration.  The model I trained only achieved an 80.0 smatch on AMR-3.  If the custom base model isn't making the difference, then I'm not sure what's causing the lower score.

There are a few model weights in the new transformers version that are different from your pre-trained model so I can't run that in the new code to test the new code.

If you have any ideas what might be causing the lower score let me know, otherwise I'll play around with hyperparameters etc.. and see if I can get it back to 83 smatch with the AMR-3 corpus and the newer xfm model.

**Comment by bjascob** [comment]
I have this working now and I'm getting an 83.5 smatch score when I remove the :wiki tags from the gold and predicted datasets.

The issue was that I misunderstood what the config option "remove_wiki=True" does.  This doesn't remove the :wiki tag, it replaces the object with a plus sign (ie.. :wiki +).  Unfortunately the config option doesn't impact the gold data, which is copied verbatim from the source files to a single file for later smatch score.  This means that if you set "remove_wiki=True" in the config, all the scores during training will be lower since you're comparing a dataset with complete :wiki tags to one trained to generate ":wiki +".
