### ISSUE TITLE
Parameter mismatch in predict_amrs_from_plaintext.py

### ISSUE THREAD

**Issue by xu1998hz** [SapienzaNLP/spring#14]
size mismatch for final_logits_bias: copying a param with shape torch.Size([1, 53587]) from checkpoint, the shape in current model is torch.Size([1, 53075]).
	size mismatch for model.shared.weight: copying a param with shape torch.Size([53587, 1024]) from checkpoint, the shape in current model is torch.Size([53075, 1024]).
	size mismatch for model.encoder.embed_tokens.weight: copying a param with shape torch.Size([53587, 1024]) from checkpoint, the shape in current model is torch.Size([53075, 1024]).
	size mismatch for model.decoder.embed_tokens.weight: copying a param with shape torch.Size([53587, 1024]) from checkpoint, the shape in current model is torch.Size([53075, 1024])

When I used predict_amrs_from_plaintext.py for customized text file, I had a mismatch in model config and model checkpoint. Specifically, I used AMR3.parsing.pt for model checkpoint and bart-large for model config. This is the direction of text to graph. Can you help me resolve this issue?

**Comment by xu1998hz** [comment]
My full input is:

python3 bin/predict_amrs_from_plaintext.py --texts bin/example.txt --checkpoint AMR3.parsing.pt  --model facebook/bart-large

**Comment by xu1998hz** [comment]
I actually solved this issue but looking at previous issues. Thanks!

**Comment by Mishkaldi** [comment]
I had the same issue. Could you share how to solve this?
