### ISSUE TITLE
Problems about the evaluation and the released text_to_amr 2.0 model AMR2.parsing-1.0.tar.bz2

### ISSUE THREAD

**Issue by KiroSummer** [SapienzaNLP/spring#2]
Hi, I have a question about the evaluation process.

As you mentioned in the paper, the Smatch and fine-grained scores are generated from the script provided by Damonte, Cohen, and Satta (2017) (amr-evaluation).
In the REAME.md, you said that the score from bin/predict_amr.py is higher than the one from the amr-evaluation. So, in your paper, the Smatch scores are from the bin/predict_amr.py or the amr-evaluation? 

About the text_to_amr 2.0 model ``AMR2.parsing-1.0.tar.bz2''.
I download the model and use the bin/predict_amrs.py to predict the amr-2.0 test data, I only get 83.6 Smatch (reported by predict_amrs.py).
After I use the bin/blinkify.py, I got a score of 36.8, which I think corresponds to the score of SPRING^{DFS} in Table 2. Do you prepare to release the model of the best performance SPRING^{DFS}+recat?

Thank you very much for your reply.

**Comment by rexhinab** [comment]
Hello, thank you for your questions. 

1 - The predict_amr.py calculates the score from Snowblink smatch (https://github.com/snowblink14/smatch) while the results on the paper are based on the official scripts from amr-evaluation to be comparable with other systems in the literature. 

2 - We release any other model presented in the paper on request (please send us an email). The SPRING^{DFS}+recat model though, needs the input to be recategorized apriori, which we do by using the scripts available at https://github.com/sheng-z/stog. 

Hope this answers your questions :)

**Comment by KiroSummer** [comment]
> Hello, thank you for your questions.
> 
> 1 - The predict_amr.py calculates the score from Snowblink smatch (https://github.com/snowblink14/smatch) while the results on the paper are based on the official scripts from amr-evaluation to be comparable with other systems in the literature.
> 
> 2 - We release any other model presented in the paper on request (please send us an email). The SPRING^{DFS}+recat model though, needs the input to be recategorized apriori, which we do by using the scripts available at https://github.com/sheng-z/stog.
> 
> Hope this answers your questions :)

Thank you much for your reply, it helps a lot.
