### ISSUE TITLE
Questions regarding backpointers

### ISSUE THREAD

**Issue by hankcs** [SapienzaNLP/spring#3]
Hi, Michele, Rexhina and Roberto,

Thank you for your nice paper. I'm reading your codes and having some issues understanding them. Could you elaborate a bit on the role for backpointers? 

I know you are using pointers to represent variables in AMR graphs. What's not clear to me is that since you have `use_pointer_tokens=True` for each of your linearization methods, pointers will have their embeddings and the `extract_backreferences` will never return any backreferences, right? Then, the codes for caculating pointer_q and pointer_k and optimizing this "copy mechanism" are no longer needed. Am I right?

**Comment by mbevila** [comment]
Yup, sorry! You stumbled into fossils of a few preliminary experiments...

**Comment by hankcs** [comment]
Ha ha, thanks for your clarification.
