### ISSUE TITLE
What is the input format of a text file?

### ISSUE THREAD

**Issue by zhaozj89** [SapienzaNLP/spring#8]
Hi, thanks for the work. I would like to use the existing text-to-AMR tool like:

        python bin/predict_amrs.py \
            --datasets <AMR-ROOT>/data/amrs/split/test/*.txt \
            --gold-path data/tmp/amr2.0/gold.amr.txt \
            --pred-path data/tmp/amr2.0/pred.amr.txt \
            --checkpoint runs/<checkpoint>.pt \
            --beam-size 5 \
            --batch-size 500 \
            --device cuda \
            --penman-linearization --use-pointer-tokens

Could you give me an example of the `<AMR-ROOT>/data/amrs/split/test/*.txt` files? 

I have tried a plain text file, but it reported an `AssertionError` at [here](https://github.com/SapienzaNLP/spring/blob/main/spring_amr/IO.py#L23)

I do not have LDC license, and just want to use this tool for my project. Thank you.

**Comment by rexhinab** [comment]
Hello! 

For plaintext sentences please use `predict_amrs_from_plaintext.py` which expects a file with one sentence per line.

**Comment by zhaozj89** [comment]
Thank you.
