### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by Wangpeiyi9979** [SapienzaNLP/spring#9]
Hi, thanks for your nice work.
I read the code, and have a naive question:
![image](https://user-images.githubusercontent.com/42565075/130025699-be54e3e8-a818-4699-8dad-0a915b6f1ffa.png)
what is the role of the `po_logits`?  why not just use the `lm_logits` the same as the origin Bart.

**Comment by mbevila** [comment]
Previous iterations of SPRING used an extended probability distributions over vocabulary (`lm_logits`) AND pointers (`po_logits`) to previously generated tokens. So, similarly to #3 , this is basically a fossil of previous experiments, which we haven't got around to remove. It should not change anything though, simply ignore them.

**Comment by Wangpeiyi9979** [comment]
thanks for your patience!
